services:
  mysql:
    image: mysql:latest
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: nl!p3@r@@tdm!n
      MYSQL_DATABASE: peid_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: